-- Tablas maestras (sin dependencias de otras tablas transaccionales)
CREATE TABLE IF NOT EXISTS alcance_sismo (
  ID_ALCANCE INTEGER PRIMARY KEY AUTO_INCREMENT,
  DESCRIPCION TEXT,
  NOMBRE TEXT
);

CREATE TABLE IF NOT EXISTS clasificacion_sismo (
  ID_CLASIFICACION INTEGER PRIMARY KEY AUTO_INCREMENT,
  KM_PROFUNDIDAD_DESDE REAL,
  KM_PROFUNDIDAD_HASTA REAL,
  NOMBRE TEXT
);

CREATE TABLE IF NOT EXISTS origen_de_generacion (
  ID_ORIGEN INTEGER PRIMARY KEY AUTO_INCREMENT,
  DESCRIPCION TEXT,
  NOMBRE TEXT
);

CREATE TABLE IF NOT EXISTS estado (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  AMBITO TEXT,
  NOMBRE_ESTADO TEXT
);

CREATE TABLE IF NOT EXISTS tipo_de_dato (
  ID_TIPO BIGINT PRIMARY KEY AUTO_INCREMENT,
  DENOMINACION TEXT,
  NOMBRE_UNIDAD_MEDIDA TEXT,
  VALOR_UMBRAL REAL
);

CREATE TABLE IF NOT EXISTS estacion_sismologica (
  CODIGO_ESTACION TEXT PRIMARY KEY,
  DOCUMENTO_CERT_ADQ TEXT,
  FECHA_SOLICITUD_CERT DATE,
  LATITUD REAL,
  LONGITUD REAL,
  NOMBRE TEXT,
  NRO_CERT_ADQUISICION TEXT
);

CREATE TABLE IF NOT EXISTS magnitud_ritcher (
  ID_MAGNITUD_RITCHER INTEGER PRIMARY KEY AUTO_INCREMENT,
  NUMERO REAL,
  DESCRIPCION_MAGNITUD TEXT
);

CREATE TABLE IF NOT EXISTS empleado (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE TEXT NOT NULL,
    APELLIDO TEXT NOT NULL,
    MAIL TEXT NOT NULL UNIQUE,
    TELEFONO BIGINT
);

---

-- Tablas transaccionales (Orden de creación crucial para claves foráneas)

-- 1. Crear Sismografo (referenciado por serie_temporal)
CREATE TABLE IF NOT EXISTS sismografo (
  IDENTIFICADOR TEXT PRIMARY KEY,
  ID_ADQUISICION INTEGER,
  NRO_SERIE TEXT,
  CODIGO_ESTACION TEXT REFERENCES ESTACION_SISMOLOGICA(CODIGO_ESTACION)
);

-- 2. Crear EventoSismico (referenciado por serie_temporal y cambio_estado)
CREATE TABLE IF NOT EXISTS evento_sismico (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  FECHA_HORA_FIN DATETIME,
  FECHA_HORA_OCURRENCIA DATETIME,
  LATITUD_EPICENTRO REAL,
  LONGITUD_EPICENTRO REAL,
  LATITUD_HIPOCENTRO REAL,
  LONGITUD_HIPOCENTRO REAL,
  VALOR_MAGNITUD REAL,
  ALCANCE_SISMO_ID INTEGER REFERENCES alcance_sismo(ID_ALCANCE),
  CLASIFICACION_SISMO_ID INTEGER REFERENCES clasificacion_sismo(ID_CLASIFICACION),
  ESTADO_ACTUAL_ID INTEGER REFERENCES estado(ID),
  MAGNITUD_RITCHER_ID INTEGER REFERENCES magnitud_ritcher(ID_MAGNITUD_RITCHER),
  ORIGEN_GENERACION_ID INTEGER REFERENCES origen_de_generacion(ID_ORIGEN)
);

-- 3. Crear SerieTemporal (referencia sismografo y evento_sismico)
CREATE TABLE IF NOT EXISTS serie_temporal (
  ID_SERIE INTEGER PRIMARY KEY AUTO_INCREMENT,
  CONDICION_ALARMA TEXT,
  FECHA_HORA_INICIO_REG_MUESTREO DATETIME,
  FECHA_HORA_REGISTROS DATETIME,
  FRECUENCIA_MUESTREO REAL,
  ID_SISMOGRAFO TEXT REFERENCES sismografo(IDENTIFICADOR),
  EVENTO_SISMICO_ID INTEGER REFERENCES evento_sismico(ID)
);

-- 4. Crear MuestraSismica (referencia serie_temporal)
CREATE TABLE IF NOT EXISTS muestra_sismica (
  ID_MUESTRA_SISMICA INTEGER PRIMARY KEY AUTO_INCREMENT,
  FECHA_HORA_MUESTRA DATETIME,
  ID_SERIE INTEGER REFERENCES serie_temporal(ID_SERIE)
);

-- 5. Crear DetalleMuestraSismica (referencia muestra_sismica y tipo_de_dato)
CREATE TABLE IF NOT EXISTS detalle_muestra_sismica (
  ID_DETALLE_MUESTRA_SISMICA INTEGER PRIMARY KEY AUTO_INCREMENT,
  ID_TIPO INTEGER REFERENCES TIPO_DE_DATO(ID_TIPO),
  VALOR REAL,
  ID_MUESTRA_SISMICA INTEGER REFERENCES muestra_sismica(ID_MUESTRA_SISMICA)
);

-- 6. Crear CambioEstado (referencia estado, empleado y evento_sismico)
CREATE TABLE IF NOT EXISTS cambio_estado (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  ESTADO_ID INTEGER NOT NULL REFERENCES ESTADO(ID),
  FECHA_HORA_INICIO DATETIME NOT NULL,
  FECHA_HORA_FIN DATETIME,
  RESPONSABLE_ID BIGINT REFERENCES EMPLEADO(ID),
  EVENTO_SISMICO_ID INTEGER REFERENCES EVENTO_SISMICO(ID)
);
